require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ZipCodesController do

  # This should return the minimal set of attributes required to create a valid
  # ZipCode. As you add validations to ZipCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "zip_code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZipCodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all zip_codes as @zip_codes" do
      zip_code = ZipCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:zip_codes).should eq([zip_code])
    end
  end

  describe "GET show" do
    it "assigns the requested zip_code as @zip_code" do
      zip_code = ZipCode.create! valid_attributes
      get :show, {:id => zip_code.to_param}, valid_session
      assigns(:zip_code).should eq(zip_code)
    end
  end

  describe "GET new" do
    it "assigns a new zip_code as @zip_code" do
      get :new, {}, valid_session
      assigns(:zip_code).should be_a_new(ZipCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested zip_code as @zip_code" do
      zip_code = ZipCode.create! valid_attributes
      get :edit, {:id => zip_code.to_param}, valid_session
      assigns(:zip_code).should eq(zip_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ZipCode" do
        expect {
          post :create, {:zip_code => valid_attributes}, valid_session
        }.to change(ZipCode, :count).by(1)
      end

      it "assigns a newly created zip_code as @zip_code" do
        post :create, {:zip_code => valid_attributes}, valid_session
        assigns(:zip_code).should be_a(ZipCode)
        assigns(:zip_code).should be_persisted
      end

      it "redirects to the created zip_code" do
        post :create, {:zip_code => valid_attributes}, valid_session
        response.should redirect_to(ZipCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved zip_code as @zip_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        ZipCode.any_instance.stub(:save).and_return(false)
        post :create, {:zip_code => { "zip_code" => "invalid value" }}, valid_session
        assigns(:zip_code).should be_a_new(ZipCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ZipCode.any_instance.stub(:save).and_return(false)
        post :create, {:zip_code => { "zip_code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested zip_code" do
        zip_code = ZipCode.create! valid_attributes
        # Assuming there are no other zip_codes in the database, this
        # specifies that the ZipCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ZipCode.any_instance.should_receive(:update).with({ "zip_code" => "MyString" })
        put :update, {:id => zip_code.to_param, :zip_code => { "zip_code" => "MyString" }}, valid_session
      end

      it "assigns the requested zip_code as @zip_code" do
        zip_code = ZipCode.create! valid_attributes
        put :update, {:id => zip_code.to_param, :zip_code => valid_attributes}, valid_session
        assigns(:zip_code).should eq(zip_code)
      end

      it "redirects to the zip_code" do
        zip_code = ZipCode.create! valid_attributes
        put :update, {:id => zip_code.to_param, :zip_code => valid_attributes}, valid_session
        response.should redirect_to(zip_code)
      end
    end

    describe "with invalid params" do
      it "assigns the zip_code as @zip_code" do
        zip_code = ZipCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ZipCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => zip_code.to_param, :zip_code => { "zip_code" => "invalid value" }}, valid_session
        assigns(:zip_code).should eq(zip_code)
      end

      it "re-renders the 'edit' template" do
        zip_code = ZipCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ZipCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => zip_code.to_param, :zip_code => { "zip_code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested zip_code" do
      zip_code = ZipCode.create! valid_attributes
      expect {
        delete :destroy, {:id => zip_code.to_param}, valid_session
      }.to change(ZipCode, :count).by(-1)
    end

    it "redirects to the zip_codes list" do
      zip_code = ZipCode.create! valid_attributes
      delete :destroy, {:id => zip_code.to_param}, valid_session
      response.should redirect_to(zip_codes_url)
    end
  end

end
